imports:
    - javascript
    - php

tools:
  external_code_coverage: true
  php_changetracking: true
  php_sim: true
  php_pdepend: true
  sensiolabs_security_checker: true
  php_mess_detector: true
  php_code_sniffer:
    config:
      standard: "PSR1"
  php_analyzer:
    config:
        metrics_lack_of_cohesion_methods:
            enabled: true

filter:
    excluded-paths: [ spec/*, vendor/*, bin/* ]